version: '2'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx1g
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data/elastic/esdata1:/usr/share/elasticsearch/data
    #  - ./config/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    mem_limit: 1536m


  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    depends_on: 
      - elastic
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elastic:9200
    ports:
      - 5601:5601

  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql/master:/var/lib/mysql
    ports:
      - 13311:3306
    environment:
      MYSQL_ROOT_PASSWORD: alex
      MYSQL_DATABASE: ad
      MYSQL_USER: ad
      MYSQL_PASSWORD: ad

  redis:
    image: redis

  php:
    build: ./build/php
    depends_on: 
      - elastic 
      - db
      - redis
    volumes:
      - ./code:/code
